### ISSUE TITLE
[FEAT] Possible to replace Pod Identity with Workload Identity as Pod Identity is deprecated

### ISSUE THREAD

**Issue by ibrt2016** [claranet/terraform-azurerm-aks#14]
### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

Possible to replace Pod Identity with Workload Identity as Pod Identity is deprecated

### Description

Possible to replace Pod Identity with Workload Identity as Pod Identity is deprecated

### New or Affected Resource(s)/Data Source(s)

azurerm for pod identity

**Comment by BzSpi** [comment]
Hello @ibrt2016 ,

We are in the process of deprecating this module because of a unsatisfying design (k8s deployment within the module for examples) and numerous Azure changes since the initial release (the one you point at for example).
The future module, which is very close to first release will be named [aks-light](https://github.com/claranet/terraform-azurerm-aks-light) and will focus on infrastructure only.

I'm sorry but this issue will very probably not be implemented.

**Comment by mloskot** [comment]
@ibrt2016 I'm happy to confirm the [aks-light](https://github.com/claranet/terraform-azurerm-aks-light) works perfectly well and allowed me to migrate my AKS clusters to from AAD Pod Identity to Workload Identity.

FYA @BzSpi One showstopper was this issue, which I thing is as regression
- https://github.com/claranet/terraform-azurerm-aks-light/issues/5

but I've solved it by temporarily vendoring the module, see https://github.com/claranet/terraform-azurerm-aks-light/issues/5#issuecomment-1848394273

**Comment by BzSpi** [comment]
Hi @mloskot 

Thanks a lot for your feedback !

We'll take a look at the other issue.
